[package]
name = "macros-impl"
version = "0.1.0"
edition = "2021"

[dependencies]
proc-macro2 = { workspace = true }
quote = "1.0.33"
syn = { version = "2.0.43", features = ["full", "extra-traits"] }

[dev-dependencies]
pretty_assertions = "1.4.0"
